/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddOrgDialog: typeof import('./src/components/auth/AddOrgDialog.vue')['default']
    AutoComplete: typeof import('primevue/autocomplete')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    BlockViewer: typeof import('./src/components/BlockViewer.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    Drawer: typeof import('primevue/drawer')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    EmailTagInput: typeof import('./src/components/auth/EmailTagInput.vue')['default']
    FeatureList: typeof import('./src/components/ui/features/FeatureList.vue')['default']
    HSAutoComplete: typeof import('./src/components/ui/forms/HSAutoComplete.vue')['default']
    HSAutoCompleteExample: typeof import('./src/components/ui/forms/HSAutoCompleteExample.vue')['default']
    HSFormContainer: typeof import('./src/components/ui/forms/HSFormContainer.vue')['default']
    HSFormField: typeof import('./src/components/ui/forms/HSFormField.vue')['default']
    HSFormLayout: typeof import('./src/components/ui/forms/HSFormLayout.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    InviteMembersDialog: typeof import('./src/components/auth/InviteMembersDialog.vue')['default']
    Logo: typeof import('./src/components/ui/svgs/Logo.vue')['default']
    Mail: typeof import('./src/components/ui/svgs/Mail.vue')['default']
    Message: typeof import('primevue/message')['default']
    MetadataSelection: typeof import('./src/components/metadata-visualization/MetadataSelection.vue')['default']
    OrgRegistration: typeof import('./src/components/auth/OrgRegistration.vue')['default']
    OrgSwitcher: typeof import('./src/components/auth/OrgSwitcher.vue')['default']
    OverlayBadge: typeof import('primevue/overlaybadge')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    ZeroParty: typeof import('./src/components/ui/svgs/ZeroParty.vue')['default']
    ZeroSad: typeof import('./src/components/ui/svgs/ZeroSad.vue')['default']
  }
  export interface ComponentCustomProperties {
    StyleClass: typeof import('primevue/styleclass')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
